version: '3'
services:
  drupal:
    image: bitnami/drupal:latest
    ports:
      - '80:8080'
    environment:
      - MARIADB_HOST=db
      - MARIADB_PORT_NUMBER=3306
      - DRUPAL_DATABASE_USER=YAM428
      - DRUPAL_DATABASE_PASSWORD=30719104
      - DRUPAL_DATABASE_NAME=final
    depends_on:
      - db

  db:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_USER=YAM428
      - MARIADB_PASSWORD=30719104
      - MARIADB_DATABASE=final

  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - drupal

  certbot:
  image: certbot/certbot
  command: certonly --non-interactive --agree-tos --email ugurarpaci1@gmail.com --webroot --webroot-path /var/www/certbot --config-dir /etc/letsencrypt
  volumes:
    - ./certbot/conf:/etc/letsencrypt
    - ./certbot/www:/var/www/certbot
  depends_on:
    - nginx

